# fly.toml app configuration file generated for bbf-api on 2024-03-30T14:37:40+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bbf-api"
primary_region = "sin"

[build]

[env]
MONGO_USER = "buatnuyul122"
MONGO_PASSWORD = "zOc3ykLnUBP7jRgQ"
MONGO_HOST = "bbf.3mtzwh6.mongodb.net"
MONGO_DB = "BBF"
MQTT_USER = "emqx"
MQTT_PASSWORD = "public"
MQTT_HOST = "broker.emqx.io"
MQTT_PORT = 1883
MQTT_TOPIC = "iot"

[[services]]
protocol = "tcp"
internal_port = 3000

[[services.ports]]
port = 80
handlers = ["http"]

[[services.ports]]
port = 443
handlers = ["tls", "http"]
[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.tcp_checks]]
interval = "10s"
timeout = "2s"
